### ISSUE TITLE
tests should be broken out into unit and integration

### ISSUE THREAD

**Issue by rockymadden** [cloud-elements/hykes-provisioner#13]
**TODO:**
- [x] unit tests should be broken out
- [x] integration tests should be broken out
- [x] `make test` should handle for changes
